#!/usr/bin/env python3
"""
build_data_js.py — Convert data/cards.json + data/changelog.json into
data/data.js (window.ARCHIVE_DATA / window.ARCHIVE_CHANGELOG) so the site
works from file:// with no server, and CORS never bites.

Run after sync_cards.py. Idempotent.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))


def load(path, default):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return default


def main():
    cards = load(os.path.join(ROOT, "data", "cards.json"), {"meta": {}, "cards": []})
    changelog = load(os.path.join(ROOT, "data", "changelog.json"), [])
    meta = dict(cards.get("meta", {}))
    # extra ISO timestamp for NEW-badge logic
    if "synced_at" in meta and "synced_at_iso" not in meta:
        iso = meta["synced_at"].replace(" UTC", "Z").replace(" ", "T")
        meta["synced_at_iso"] = iso
    payload = {"meta": meta, "cards": cards.get("cards", [])}
    out = (
        "// Generated by build_data_js.py — do not edit by hand.\n"
        f"window.ARCHIVE_DATA = {json.dumps(payload, ensure_ascii=False)};\n"
        f"window.ARCHIVE_CHANGELOG = {json.dumps(changelog, ensure_ascii=False)};\n"
    )
    dest = os.path.join(ROOT, "data", "data.js")
    with open(dest, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"OK: wrote {dest} ({len(payload['cards'])} cards, {len(changelog)} changelog entries)")


if __name__ == "__main__":
    main()
