#!/usr/bin/env python3
"""
build_data_js.py — Convert data/cards.json + data/changelog.json into
data/data.js (window.ARCHIVE_DATA / window.ARCHIVE_CHANGELOG) so the site
works from file:// with no server, and CORS never bites.

Run after sync_cards.py. Idempotent.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))


def load(path, default):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return default


def main():
    cards = load(os.path.join(ROOT, "data", "cards.json"), {"meta": {}, "cards": []})
    changelog = load(os.path.join(ROOT, "data", "changelog.json"), [])
    meta = dict(cards.get("meta", {}))
    # extra ISO timestamp for NEW-badge logic
    if "synced_at" in meta and "synced_at_iso" not in meta:
        iso = meta["synced_at"].replace(" UTC", "Z").replace(" ", "T")
        meta["synced_at_iso"] = iso
    payload = {"meta": meta, "cards": cards.get("cards", [])}
    out = (
        "// Generated by build_data_js.py — do not edit by hand.\n"
        f"window.ARCHIVE_DATA = {json.dumps(payload, ensure_ascii=False)};\n"
        f"window.ARCHIVE_CHANGELOG = {json.dumps(changelog, ensure_ascii=False)};\n"
    )
    dest = os.path.join(ROOT, "data", "data.js")
    with open(dest, "w", encoding="utf-8") as f:
        f.write(out)
    # cache-bust: bump the ?v= on the data.js reference in index.html so
    # returning visitors always load fresh card data (Pages/browser caches)
    idx = os.path.join(ROOT, "index.html")
    try:
        html = open(idx, encoding="utf-8").read()
        import re
        html_new = re.sub(r'data/data\.js\?v=\d+', f'data/data.js?v={int(__import__("time").time())}', html)
        if "data/data.js?v=" not in html_new:
            html_new = html_new.replace('src="data/data.js"', f'src="data/data.js?v={int(__import__("time").time())}"')
        if html_new != html:
            with open(idx, "w", encoding="utf-8") as f:
                f.write(html_new)
            print("OK: bumped data.js cache-buster in index.html")
    except FileNotFoundError:
        pass
    print(f"OK: wrote {dest} ({len(payload['cards'])} cards, {len(changelog)} changelog entries)")


if __name__ == "__main__":
    main()
